In [2]:
# pip install numpy
import numpy as np

creating a  numpy array

In [3]:
x = [1, 2, 3, 4, 5]
nx = np.array(x)

In [4]:
nx.ndim

1

In [9]:
y = [[1,2,3],[4,5,6]]
ny = np.array(y)

In [11]:
ny.ndim

2

In [10]:
print(nx)
print(ny)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [12]:
nz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
nz.ndim

2

In [14]:
nx.shape

(5,)

In [15]:
ny.shape

(2, 3)

In [16]:
nz.shape

(3, 3)

In [23]:
y =np.linspace(0,100,5)
print(y)

[  0.  25.  50.  75. 100.]


In [25]:
a = np.random.rand(6)
print(a)

[0.87284624 0.87151315 0.42332132 0.45004595 0.04928478 0.02886366]


In [29]:
b = np.random.rand(3,3)
print(b)

[[0.83133022 0.43694921 0.23365976]
 [0.26602387 0.55283338 0.55746205]
 [0.80988939 0.20348723 0.19388852]]


In [34]:
c = np.random.randint(0, 101, (3,3))
print(c)

[[13 82 79]
 [82 15 31]
 [22 91 86]]


In [54]:
d = np.random.choice(['❌','⭕'], (3,3))
print(d)

[['⭕' '❌' '❌']
 ['❌' '⭕' '❌']
 ['❌' '❌' '❌']]


In [57]:
o=np.ones((3,3), dtype=int)
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [61]:
e =np.eye(6, dtype=int)
print(e)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [64]:
np.diag(nx)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [69]:
c.transpose()

array([[13, 82, 22],
       [82, 15, 91],
       [79, 31, 86]])

In [70]:
print(c)
print()
print(c.T)

[[13 82 79]
 [82 15 31]
 [22 91 86]]

[[13 82 22]
 [82 15 91]
 [79 31 86]]


In [71]:
c.size # number of elements

9

In [72]:
c.dtype

dtype('int32')

In [73]:
x = np.array([[6,9],[6,9]])
y = np.array([[3,2],[1,3]])

In [74]:
(x+y)

array([[ 9, 11],
       [ 7, 12]])

In [75]:
x + 5 

array([[11, 14],
       [11, 14]])

In [76]:
x.dot(y)

array([[27, 39],
       [27, 39]])

In [77]:
x*y

array([[18, 18],
       [ 6, 27]])

In [80]:
np.cross(x,y)

array([-15,   9])

In [82]:
np.sin(x)

array([[-0.2794155 ,  0.41211849],
       [-0.2794155 ,  0.41211849]])

In [85]:
y.argmin()

2

In [86]:
y

array([[3, 2],
       [1, 3]])

In [87]:
x.max()

9

In [94]:
r=np.random.randint(-101,101,(5,5))
r

array([[ 20, -68, -52,  42,  41],
       [-11, -23,  35,  96, -54],
       [ 63, -27, -53, -83,  88],
       [-64,  58,  16,  29,  92],
       [-10, -17, -10, -49,  19]])

In [95]:
r.max(), r.min()

(96, -83)

In [96]:
print(r.sum(), r.mean(), r.std(), r.var(), r.prod())

78 3.12 51.90323303995619 2693.9456 -2147483648


In [ ]:
x=np.random.randint(0,101,(3,3))
y=np.random.randint(0,101,(3,3))
print(x,)

In [ ]:
# top 5 rows
print(a[:5])
# last 3 rows
print(a[-3:])

In [ ]:
# 1 column
print(a[:,1])
# first 