In [3]:
# pip install numpy
import numpy as np

creating a  numpy array

In [4]:
x = [1, 2, 3, 4, 5]
nx = np.array(x)

In [5]:
nx.ndim

1

In [6]:
y = [[1,2,3],[4,5,6]]
ny = np.array(y)

In [12]:
ny.ndim

2

In [7]:
print(nx)
print(ny)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [8]:
nz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
nz.ndim

2

In [10]:
nx.shape

(5,)

In [11]:
ny.shape

(2, 3)

In [16]:
nz.shape

(3, 3)

In [17]:
y =np.linspace(0,100,5)
print(y)

[  0.  25.  50.  75. 100.]


In [12]:
a = np.random.rand(6)
print(a)

[0.4120193  0.06764944 0.29708666 0.64141405 0.4954619  0.01976682]


In [13]:
b = np.random.rand(3,3)
print(b)

[[0.42870404 0.11950374 0.53826174]
 [0.59651987 0.65126507 0.47134356]
 [0.13114322 0.11983017 0.78564726]]


In [14]:
c = np.random.randint(0, 101, (3,3))
print(c)

[[89 27 83]
 [93  9 27]
 [49 29 27]]


In [15]:
d = np.random.choice(['❌','⭕'], (3,3))
print(d)

[['❌' '❌' '❌']
 ['❌' '❌' '⭕']
 ['⭕' '⭕' '⭕']]


In [16]:
o=np.ones((3,3), dtype=int)
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
e =np.eye(6, dtype=int)
print(e)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [18]:
np.diag(nx)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [19]:
c.transpose()

array([[89, 93, 49],
       [27,  9, 29],
       [83, 27, 27]])

In [20]:
print(c)
print()
print(c.T)

[[89 27 83]
 [93  9 27]
 [49 29 27]]

[[89 93 49]
 [27  9 29]
 [83 27 27]]


In [21]:
c.size # number of elements

9

In [22]:
c.dtype

dtype('int32')

In [23]:
x = np.array([[6,9],[6,9]])
y = np.array([[3,2],[1,3]])

In [24]:
(x+y)

array([[ 9, 11],
       [ 7, 12]])

In [25]:
x + 5 

array([[11, 14],
       [11, 14]])

In [26]:
x.dot(y)

array([[27, 39],
       [27, 39]])

In [27]:
x*y

array([[18, 18],
       [ 6, 27]])

In [28]:
np.cross(x,y)

array([-15,   9])

In [29]:
np.sin(x)

array([[-0.2794155 ,  0.41211849],
       [-0.2794155 ,  0.41211849]])

In [30]:
y.argmin()

2

In [31]:
y

array([[3, 2],
       [1, 3]])

In [32]:
x.max()

9

In [33]:
r=np.random.randint(-101,101,(5,5))
r

array([[-51,  68, -21,  56, -86],
       [ 97, -35, -43, -44,  63],
       [-23, -84,  71, -18,  92],
       [ 44, -83,  50, -69, -62],
       [-76, -55, -39,  90, -51]])

In [34]:
r.max(), r.min()

(97, -86)

In [35]:
print(r.sum(), r.mean(), r.std(), r.var(), r.prod())

-209 -8.36 62.35567656597112 3888.2304 430964736


In [36]:
x=np.random.randint(0,101,(3,3))
y=np.random.randint(0,101,(3,3))
print(x,y, sep='\n\n')

[[56 83 95]
 [46 73 22]
 [62 57  1]]

[[63 47 38]
 [87 82 53]
 [44 47 48]]


In [37]:
x*y # hadamard product

array([[3528, 3901, 3610],
       [4002, 5986, 1166],
       [2728, 2679,   48]])

In [38]:
x @ y # matrix product (dot product)

array([[14929, 13903, 11087],
       [10217,  9182,  6673],
       [ 8909,  7635,  5425]])

# numpy slicing (in 2D array)
```
arr[row_start:row_end, col_start:col_end]
```

In [47]:
# 10 * 5 matrix
a = np.random.randint(10, 100, (10,5))
a

array([[75, 31, 48, 40, 89],
       [12, 99, 85, 71, 72],
       [97, 70, 60, 93, 41],
       [64, 86, 74, 25, 66],
       [58, 62, 59, 12, 17],
       [66, 89, 32, 73, 55],
       [65, 19, 22, 74, 21],
       [26, 53, 11, 81, 49],
       [54, 85, 52, 70, 92],
       [84, 98, 55, 78, 53]])

In [40]:
# top 5 rows
print(a[:5])
# last 3 rows
print(a[-3:])

[[55 90 90 57 17]
 [79 82 46 29 85]
 [30 33 40 17 56]
 [90 89 81 72 95]
 [30 62 72 74 81]]
[[92 84 25 87 46]
 [12 83 26 96 23]
 [47 67 68 44 47]]


In [41]:
# 1 column
print(a[:,1])
# first 3 columns 
print(a[:,:3])
# last 3 columns
print(a[:, -3:])
# 0,2,4 columns
print(a[:,[0,2,4]])
# first 5 row, first 3 columns
print(a[:5, :3])


[90 82 33 89 62 37 18 84 83 67]
[[55 90 90]
 [79 82 46]
 [30 33 40]
 [90 89 81]
 [30 62 72]
 [36 37 78]
 [48 18 65]
 [92 84 25]
 [12 83 26]
 [47 67 68]]
[[90 57 17]
 [46 29 85]
 [40 17 56]
 [81 72 95]
 [72 74 81]
 [78 89 15]
 [65 14 15]
 [25 87 46]
 [26 96 23]
 [68 44 47]]
[[55 90 17]
 [79 46 85]
 [30 40 56]
 [90 81 95]
 [30 72 81]
 [36 78 15]
 [48 65 15]
 [92 25 46]
 [12 26 23]
 [47 68 47]]
[[55 90 90]
 [79 82 46]
 [30 33 40]
 [90 89 81]
 [30 62 72]]


In [42]:
# 1 column
print(a[:,1])
# first 3 columns 
print(a[:,:3])
# last 3 columns
print(a[:, -3:])
# 0,2,4 columns
print(a[:,[0,2,4]])
# first 5 row, first 3 columns
print(a[:5, :3])


[90 82 33 89 62 37 18 84 83 67]
[[55 90 90]
 [79 82 46]
 [30 33 40]
 [90 89 81]
 [30 62 72]
 [36 37 78]
 [48 18 65]
 [92 84 25]
 [12 83 26]
 [47 67 68]]
[[90 57 17]
 [46 29 85]
 [40 17 56]
 [81 72 95]
 [72 74 81]
 [78 89 15]
 [65 14 15]
 [25 87 46]
 [26 96 23]
 [68 44 47]]
[[55 90 17]
 [79 46 85]
 [30 40 56]
 [90 81 95]
 [30 72 81]
 [36 78 15]
 [48 65 15]
 [92 25 46]
 [12 26 23]
 [47 68 47]]
[[55 90 90]
 [79 82 46]
 [30 33 40]
 [90 89 81]
 [30 62 72]]
